### PR TITLE
Add contents for slide 5 to 8

### PR DESCRIPTION
**Pull request by h4xr**
Add slide 5 content

Add slide 6 and 7 content

Add slide 8 content

Add styling

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Although I can see you've added this in HTML but content in some slide is not appearing. Can you please check? @h4xr

**Comment by h4xr** [comment]
Rebased the commit :)

**Comment by CuriousLearner** [comment]
@h4xr Looks good, just squash and we're ready to go.

**Comment by CuriousLearner** [comment]
I'm merging in. Thanks @h4xr

**Pull request merged**
